# Generated by Django 3.2.10 on 2022-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_google',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
