# Generated by Django 3.2.10 on 2022-05-15 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_quote_save_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='save_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
