# Generated by Django 3.2.10 on 2022-05-24 07:58
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='book_author',
            field=models.CharField(default='Book author(Recognized)', max_length=20,
                                   validators=[django.core.validators.MinLengthValidator(limit_value=2, message=None)],
                                   verbose_name='Book author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_title',
            field=models.CharField(default='Book title(Recognized)', max_length=20,
                                   validators=[django.core.validators.MinLengthValidator(limit_value=2, message=None)],
                                   verbose_name='Quote Title'),
        ),
    ]
