# Generated by Django 3.2.10 on 2022-05-24 13:42
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0002_auto_20220524_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='height',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='width',
        ),
        migrations.AddField(
            model_name='quote',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='book_author',
            field=models.CharField(blank=True, max_length=20,
                                   validators=[django.core.validators.MinLengthValidator(limit_value=2, message=None)],
                                   verbose_name='Book author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_title',
            field=models.CharField(blank=True, max_length=20,
                                   validators=[django.core.validators.MinLengthValidator(limit_value=2, message=None)],
                                   verbose_name='Quote Title'),
        ),
    ]
