# Generated by Django 3.2.10 on 2022-05-25 14:46
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0004_alter_quote_quote_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='styles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
