# Generated by Django 3.2.10 on 2022-05-30 09:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0005_quote_styles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes_by_user',
        ),
    ]
