# Generated by Django 3.2.10 on 2022-05-30 13:06
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0006_remove_quote_likes_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='save_users',
        ),
    ]
