# Generated by Django 3.2.10 on 2022-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_remove_quote_save_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent'),
        ),
    ]
