# Generated by Django 3.2.10 on 2022-05-17 14:20
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds',
                                    validators=[django.core.validators.validate_image_file_extension,
                                                django.core.validators.FileExtensionValidator(
                                                    allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
    ]
